export const DELEGATIONS_FETCH_SUCCESS = 'DELEGATIONS_FETCH_SUCCESS';
export const DELEGATIONS_FETCH_ERROR = 'DELEGATIONS_FETCH_ERROR';
export const DELEGATIONS_STATUS_SUCCESS = 'DELEGATIONS_STATUS_SUCCESS';
