export const TX_DELEGATE_AMOUNT_SET = 'TX_DELEGATE_AMOUNT_SET';
export const TX_DELEGATE_MEMO_SET = 'TX_DELEGATE_MEMO_SET';
export const TX_DELEGATE_MODAL_SHOW = 'TX_DELEGATE_MODAL_SHOW';
export const TX_DELEGATE_MODAL_HIDE = 'TX_DELEGATE_MODAL_HIDE';
