export const KEYSTORE_MNEMONIC_SET = 'KEYSTORE_MNEMONIC_SET';
export const KEYSTORE_COIN_TYPE_SET = 'KEYSTORE_COIN_TYPE_SET';
export const KEYSTORE_COIN_TYPE_MODAL_HIDE = 'KEYSTORE_COIN_TYPE_MODAL_HIDE';

export const KEYSTORE_PASSWORD_SET = 'KEYSTORE_PASSWORD_SET';
export const KEYSTORE_MNEMONIC_MODAL_SHOW = 'KEYSTORE_MNEMONIC_MODAL_SHOW';
export const KEYSTORE_MNEMONIC_MODAL_NEXT = 'KEYSTORE_MNEMONIC_MODAL_NEXT';
export const KEYSTORE_MNEMONIC_MODAL_HIDE = 'KEYSTORE_MNEMONIC_MODAL_HIDE';
export const KEYSTORE_PASSWORD_MODAL_SHOW = 'KEYSTORE_PASSWORD_MODAL_SHOW';
export const KEYSTORE_PASSWORD_MODAL_HIDE = 'KEYSTORE_PASSWORD_MODAL_HIDE';
export const KEYSTORE_RESULT_MODAL_SHOW = 'KEYSTORE_RESULT_MODAL_SHOW';
export const KEYSTORE_RESULT_MODAL_HIDE = 'KEYSTORE_RESULT_MODAL_HIDE';
export const KEYSTORE_RESULT_SET = 'KEYSTORE_RESULT_SET';