export const TX_RE_DELEGATE_AMOUNT_SET = 'TX_RE_DELEGATE_AMOUNT_SET';
export const TX_RE_DELEGATE_TO_ADDRESS_SET = 'TX_RE_DELEGATE_TO_ADDRESS_SET';
export const TX_RE_DELEGATE_MODAL_SHOW = 'TX_RE_DELEGATE_MODAL_SHOW';
export const TX_RE_DELEGATE_MODAL_HIDE = 'TX_RE_DELEGATE_MODAL_HIDE';
