export const  REWARDS_FETCH_SUCCESS = 'REWARDS_FETCH_SUCCESS';
export const REWARDS_FETCH_ERROR = 'REWARDS_FETCH_ERROR';
export const REWARDS_FETCH_IN_PROGRESS = 'REWARDS_FETCH_IN_PROGRESS';
export const  REWARDS_LIST_FETCH_SUCCESS = 'REWARDS_LIST_FETCH_SUCCESS';
export const FETCH_VALIDATOR_WITH_ADDRESS_ERROR = 'FETCH_VALIDATOR_WITH_ADDRESS_ERROR';
export const FETCH_VALIDATORS_REWARDS_SUCCESS = 'FETCH_VALIDATORS_REWARDS_SUCCESS';
export const FETCH_VALIDATOR_COMMISSION_INFO_SUCCESS = 'FETCH_VALIDATOR_COMMISSION_INFO_SUCCESS';
