export const TX_SEND_AMOUNT_SET = 'TX_SEND_AMOUNT_SET';
export const TX_SEND_TOKEN_SET = 'TX_SEND_TOKEN_SET';
export const TX_SEND_ADDRESS_SET = 'TX_SEND_ADDRESS_SET';
export const TX_SEND_IN_PROGRESS = 'TX_SEND_IN_PROGRESS';
export const TX_SEND_RESPONSE = 'TX_SEND_RESPONSE';
export const TX_SEND_SUCCESS = 'TX_SEND_SUCCESS';
export const TX_SEND_FAILED = 'TX_SEND_FAILED';
export const TX_SEND_MEMO_SET = 'TX_SEND_MEMO_SET';
