export const TRANSACTIONS_FETCH_SUCCESS = 'TRANSACTIONS_FETCH_SUCCESS';
export const TRANSACTIONS_FETCH_ERROR = 'TRANSACTIONS_FETCH_ERROR';
export const TRANSACTIONS_IN_PROGRESS = 'TRANSACTIONS_IN_PROGRESS';