export const TX_DELEGATE_MODAL_SHOW = 'TX_DELEGATE_MODAL_SHOW';
export const TX_DELEGATE_MODAL_HIDE = 'TX_DELEGATE_MODAL_HIDE';

export const TX_DELEGATE_SUCCESS = 'TX_DELEGATE_SUCCESS';
export const TX_DELEGATE_ERROR = 'TX_DELEGATE_ERROR';
