export const UNBOND_DELEGATIONS_FETCH_SUCCESS = 'UNBOND_DELEGATIONS_FETCH_SUCCESS';
export const UNBOND_DELEGATIONS_FETCH_ERROR = 'UNBOND_DELEGATIONS_FETCH_ERROR';
export const UNBOND_DELEGATIONS_LIST = 'UNBOND_DELEGATIONS_LIST';
export const UNBOND_DELEGATIONS_FETCH_IN_PROGRESS = 'UNBOND_DELEGATIONS_FETCH_IN_PROGRESS';