export const FETCH_ACTIVE_VALIDATORS_SUCCESS = 'FETCH_ACTIVE_VALIDATORS_SUCCESS';
export const FETCH_INACTIVE_VALIDATORS_SUCCESS = 'FETCH_INACTIVE_VALIDATORS_SUCCESS';
export const FETCH_VALIDATORS_ERROR = 'FETCH_VALIDATORS_ERROR';
export const FETCH_VALIDATORS_SUCCESS = 'FETCH_VALIDATORS_SUCCESS';
export const FETCH_VALIDATORS_IN_PROGRESS = 'FETCH_VALIDATORS_IN_PROGRESS';
export const FETCH_VALIDATOR_WITH_ADDRESS_SUCCESS = 'FETCH_VALIDATOR_WITH_ADDRESS_SUCCESS';
