import {
  Box,
  Button,
  Container,
  Divider,
  Flex,
  Grid,
  Heading,
  Icon,
  Link,
  Stack,
  Text,
  useColorMode,
} from "@chakra-ui/react";
import Head from "next/head";
import { BsFillMoonStarsFill, BsFillSunFill } from "react-icons/bs";
import { Dependency, Product, WalletSection } from "../components";
import { dependencies, products } from "../config";
import StakedToken from "../views/StakedToken";

export default function Home() {
  const { colorMode, toggleColorMode } = useColorMode();

  return (
    <>
      <Container maxW="5xl" py={10}>
        <Head>
          <title>MantleWallet</title>
          <meta name="description" content="Generated by create cosmos app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Flex justifyContent="end" mb={4}>
          <Button variant="outline" px={0} onClick={toggleColorMode}>
            <Icon
              as={colorMode === "light" ? BsFillMoonStarsFill : BsFillSunFill}
            />
          </Button>
        </Flex>
        <Box textAlign="center">
          <Heading
            as="h1"
            fontSize={{ base: "3xl", sm: "4xl", md: "5xl" }}
            fontWeight="extrabold"
            mb={3}
          >
            MantleWallet
          </Heading>
          <Heading
            as="h1"
            fontWeight="bold"
            fontSize={{ base: "2xl", sm: "3xl", md: "4xl" }}
          >
            {/* <Text as="span">Welcome to&nbsp;</Text>
          <Text
            as="span"
            color={useColorModeValue("primary.500", "primary.200")}
          >
            CosmosKit + Next.js
          </Text> */}
          </Heading>
        </Box>
        <WalletSection />
        <StakedToken />
      </Container>
    </>
  );
}
