export const SIGN_IN_ADDRESS_MODAL_HIDE = 'SIGN_IN_ADDRESS_MODAL_HIDE';
export const SIGN_IN_ADDRESS_MODAL_SHOW = 'SIGN_IN_ADDRESS_MODAL_SHOW';
export const SET_SIGN_IN_ADDRESS = 'SET_SIGN_IN_ADDRESS';