export const SIGN_IN_COSMOSTATION_MODAL_HIDE = 'SIGN_IN_COSMOSTATION_MODAL_HIDE';
export const SIGN_IN_COSMOSTATION_MODAL_SHOW = 'SIGN_IN_COSMOSTATION_MODAL_SHOW';
export const SET_COSMOSTATION_INFO = 'SET_COSMOSTATION_INFO';