export const SIGN_IN_KEYSTORE_RESULT_MODAL_HIDE = 'SIGN_IN_KEYSTORE_RESULT_MODAL_HIDE';
export const SIGN_IN_KEYSTORE_RESULT_MODAL_SHOW = 'SIGN_IN_KEYSTORE_RESULT_MODAL_SHOW';
export const SIGN_IN_KEYSTORE_MODAL_NEXT = 'SIGN_IN_KEYSTORE_MODAL_NEXT';
export const SIGN_IN_KEYSTORE_MODAL_HIDE = 'SIGN_IN_KEYSTORE_MODAL_HIDE';
export const SIGN_IN_KEYSTORE_MODAL_SHOW = 'SIGN_IN_KEYSTORE_MODAL_SHOW';
export const SET_KEYSTORE_RESULT = 'SET_KEYSTORE_RESULT';