name: Staging

on:
  push:
    branches: [ main ]

jobs:
  Mainnet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16 ]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_TOKEN }}
        environment: 'staging-wallet'
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
