# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Staging

on:
  push:
    branches: [ main ]
jobs:
  testchain:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
        REACT_APP_API_KEY: 'https://rest-testchain.assetmantle.one'
        REACT_APP_TENDERMINT_RPC_ENDPOINT: 'https://rpc-testchain.assetmantle.one'
        REACT_APP_WEBSITE_URL: 'https://test-core-1.wallet.persistence.one'
        REACT_APP_EXPLORER_API: 'https://test-mantle-1.explorer.assetmantle.one'
        REACT_APP_MAIL_CHIMP_URL: 'https://dont.need.this.for.local.wallet.setup'
        REACT_APP_CHAIN_ID: 'mantle-1'
        REACT_APP_CHAIN_NAME: 'AssetMantle test-net'
        REACT_APP_IBC_CONFIG: 'ibcStaging.json'
        REACT_APP_GA_TRACKING_ID: ''
        REACT_APP_SENTRY_API: ''
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_TOKEN }}
        environment: 'staging-wallet'
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

  test-net-2:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: git config --global url."https://github.com/".insteadOf ssh://git@github.com/
    - run: npm ci
    - run: npm run build --if-present
      env:
        CI: false
        REACT_APP_API_KEY: 'https://rest.test-mantle-2.assetmantle.one'
        REACT_APP_TENDERMINT_RPC_ENDPOINT: 'https://rpc.test-mantle-2.assetmantle.one'
        REACT_APP_WEBSITE_URL: 'https://staging-wallet.assetmantle.one/'
        REACT_APP_EXPLORER_API: 'https://test-mantle-1.explorer.assetmantle.one'
        REACT_APP_MAIL_CHIMP_URL: 'https://dont.need.this.for.local.wallet.setup'
        REACT_APP_CHAIN_ID: 'test-mantle-2'
        REACT_APP_CHAIN_NAME: 'AssetMantle test-net-2'
        REACT_APP_IBC_CONFIG: 'ibcStaging.json'
        REACT_APP_GA_TRACKING_ID: ''
        REACT_APP_SENTRY_API: ''
    - name: Publish
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiToken: ${{ secrets.CF_TOKEN }}
        environment: 'staging-testnet-wallet'
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
